parameters:
  
    cerad_tourn_show_configs:
      
        rick:
            layout_header:  false
            layout_topmenu: false
            janrain:        false  # Social network login
            wordpress:      false  # Style sheets and javascripts
            
        default:
            layout_header:  true
            layout_topmenu: true
            janrain:        true
            wordpress:      false
            
